import streamlit as st
from pipeline.graph import build_graph

st.set_page_config(
    page_title="AI Project Analyst",
    page_icon="🧠",
    layout="centered",
)

st.title("🧠 AI Project Analyst")
st.caption(
    "Paste a rough project brief and get structured requirements, "
    "user stories, tech stack, and a delivery timeline — generated by an AI agent pipeline."
)

# --- Input ---
default_example = """Project: FreshCart - Grocery Delivery App
We want to build a mobile-first grocery delivery platform.
Key features: browse multiple stores, real-time inventory, driver notifications,
scheduled delivery windows, payment support, live order tracking.
Client wants to launch MVP within 3-4 months.
Small team, no in-house developers."""

raw_text = st.text_area(
    "Project brief",
    value=default_example,
    height=200,
    placeholder="Describe your project idea, features, constraints, and timeline...",
)

generate = st.button("✨ Generate Analysis", type="primary", use_container_width=True)

# --- Run pipeline ---
if generate:
    if not raw_text.strip():
        st.warning("Please enter a project description first.")
    else:
        with st.spinner("Running AI agent pipeline... this can take up to a minute."):
            try:
                graph = build_graph()
                result = graph.invoke({"raw_text": raw_text})
            except Exception as e:
                st.error(f"Something went wrong while generating the analysis:\n\n{e}")
                st.stop()

        st.success("Analysis complete!")

        tabs = st.tabs(
            ["📋 Key Points", "✅ Requirements", "👤 User Stories", "🛠️ Tech Stack", "📅 Timeline"]
        )

        with tabs[0]:
            st.markdown(result.get("key_points", "No output generated."))

        with tabs[1]:
            st.markdown(result.get("functional_requirements", "No output generated."))

        with tabs[2]:
            st.markdown(result.get("user_stories", "No output generated."))

        with tabs[3]:
            st.markdown(result.get("tech_stack", "No output generated."))

        with tabs[4]:
            st.markdown(result.get("timeline", "No output generated."))

        # Optional: download full report as a single markdown file
        full_report = f"""# AI Project Analysis

## Key Points
{result.get("key_points", "")}

## Functional Requirements
{result.get("functional_requirements", "")}

## User Stories
{result.get("user_stories", "")}

## Tech Stack
{result.get("tech_stack", "")}

## Timeline
{result.get("timeline", "")}
"""
        st.download_button(
            "⬇️ Download Full Report (Markdown)",
            data=full_report,
            file_name="project_analysis.md",
            mime="text/markdown",
            use_container_width=True,
        )

st.divider()
st.caption("Built with LangGraph + Groq (Llama 3.3 70B) — an agentic pipeline for automated project planning.")